// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using FlyoutNavigation;
using MonoTouch.Dialog;
using CoreGraphics;

namespace AskXhacker.iOS
{
	public partial class HomeNavigationController : UIViewController
	{
		private static Section MainSection {
			get;
			set;
		}
		private static UILabel NameLabel {
			get;
			set;
		}

		public static void UpdateName()
		{
			NameLabel.Text = string.Format("Hi {0}!",App.UserName);
			MainSection.GetContainerTableView ().ReloadData ();
		}
		public HomeNavigationController (IntPtr handle) : base (handle)
		{
			MainSection = new Section () {
				new ImageStringElement ("Watson Chat", UIImage.FromBundle ("menu_watson")),
				new ImageStringElement ("Live Chat", UIImage.FromBundle ("menu_livechat")),
				new ImageStringElement ("Settings", UIImage.FromBundle ("menu_settings")),
				//new ImageStringElement ("About", UIImage.FromBundle ("menu_about"))
			};
		}
			
		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			var navigation = new FlyoutNavigationController() {
				// Create the navigation menu
				NavigationRoot = new RootElement ("Navigation") {
					MainSection
				}
			};

			navigation.TintColor = Theme.PrimaryColor;

			var liveChatController = (LiveChatViewController)this.Storyboard.InstantiateViewController ("LiveChatViewControllerId");
			liveChatController.Navigation = navigation;
			var settings = new SettingsViewController (navigation);
			navigation.ViewControllers = new [] {
				new UINavigationController (new WatsonChatViewController (navigation)),
				new UINavigationController (liveChatController),
				new UINavigationController (settings),
			};

			MainSection.HeaderView = new UIView (new CGRect (navigation.NavigationRoot.TableView.Frame.X, navigation.NavigationRoot.TableView.Frame.Y, navigation.NavigationRoot.TableView.Frame.Width, 140)){
				BackgroundColor = UIColor.Clear
			};
			NameLabel = new UILabel (new CGRect (navigation.NavigationRoot.TableView.Frame.X + 20, 100, navigation.NavigationRoot.TableView.Frame.Width - 20, 40)) {
				Text = string.Format("Hi {0}!",App.UserName),
				TextColor = Theme.DarkPrimaryColor
			};
			MainSection.HeaderView.AddSubview (NameLabel);
			// Show the navigation view
			View.AddSubview (navigation.View);
		}
	}
}
